#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

cd /tmp # Where to download cccahe
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=13OMu3FJD-QyUaGnOXB-U1BK_i-HGux3Z' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=13OMu3FJD-QyUaGnOXB-U1BK_i-HGux3Z" -O ccache.tar.gz && rm -rf /tmp/cookies.txt # Where cccahe is located, use your ones, from where you want to download ccache!

#cd /tmp # Where to download cccahe
#time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tmp/ccache.tar.gz since my file name is ccache.tar.gz
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process
